# @host = localhost

### index
GET /api/phods HTTP/1.1
Host: {{ host }}
Accept: application/json
Authorization: Bearer {{ token }}


### show
# @prompt phod_id
GET /api/phods/{{ phod_id }}?perPage=20&page=1 HTTP/1.1
Host: {{ host }}
Accept: application/json
Authorization: Bearer {{ token }}


### store
# @prompt file
POST /api/phods HTTP/1.1
Host: {{ host }}
Accept: application/json
Authorization: Bearer {{ token }}
Content-Type: multipart/form-data; boundary=----storeForm
# boundary=----storeFormは送信するデータの目印

------storeForm
Content-Disposition: form-data; name="title"

store タイトル
------storeForm
Content-Disposition: form-data; name="place"

store 場所
------storeForm
Content-Disposition: form-data; name="body"

store 本文
------storeForm
Content-Disposition: form-data; name="image"; filename="file.jpg"

< {{ file }}
------storeForm--

#--(ハイフン)2つで終わり


### update
# @prompt file
POST /api/phods/2 HTTP/1.1
Host: {{ host }}
Accept: application/json
Authorization: Bearer {{ token }}
Content-Type: multipart/form-data; boundary=----updateForm
# boundatyは送信するデータの目印

------updateForm
Content-Disposition: form-data; name="_method"

PATCH
------updateForm
Content-Disposition: form-data; name="title"

アップデートタイトル
------updateForm
Content-Disposition: form-data; name="place"

アップデート場所
------updateForm
Content-Disposition: form-data; name="body"

アップデート本文
------updateForm
Content-Disposition: form-data; name="image"; filename="file.jpg"

< {{ file }}
------updateForm--


### destroy
# @prompt phod_id
DELETE /api/phods/{{ phod_id }} HTTP/1.1
Host: {{ host }}
Accept: application/json
Authorization: Bearer {{ token }}
