
# @host = localhost

### Get Token
# @prompt code
POST /oauth/token HTTP/1.1
Host: {{ host }}
Content-Type: application/x-www-form-urlencoded
# Authorization: Bearer {{ token }}

grant_type=authorization_code
&client_id={{ client_id }}
&client_secret={{ client_secret }}
&code={{ code }}
&redirect_uri=http://localhost


#ユーザー情報を取得
### user
GET /api/user HTTP/1.1
Host: {{ host }}
Accept: application/json
Authorization: Bearer {{ token }}

### phods
GET /api/phods HTTP/1.1
Host: {{ host }}
Accept: application/json
Authorization: Bearer {{ token }}
